export const tarjetas = [
  {
    id: 1,
    title: 'Aeropuerto',
    info: 'Hola',
    imgUrl: 'aeropuerto.jpg',
    price: 33000,
  },
  {
    id: 2,
    title: 'Glaciar Perito Moreno',
    info:'',
    imgUrl: 'perito-card.jpg',
    price: 90000,
  },
  {
    id: 3,
    title: 'El Chalten',
    imgUrl: 'fitz-roy.jpg',
    price: 200000,
  },
  {
    id: 4,
    title: 'City Tour',
    imgUrl: 'city.jfif',
    price: 60000,
  },
  {
    id: 5,
    title: 'Safari Azul',
    imgUrl: 'safariazul.jpg',
    price: 104020,
  },
  {
    id: 6,
    title: 'Lago Roca',
    imgUrl: 'lagoroca.jpeg',
    price: 2304,
  },
  {
    id: 7,
    title: 'Laguna Torre',
    imgUrl: 'lagunatorre.jpeg',
    price: 23123,
  },
  {
    id: 8,
    title: 'Laguna Capri',
    imgUrl: 'capri.jpg',
    price: 23123,
  },
  {
    id: 9,
    title: 'Ushuaia',
    imgUrl: 'entrada-ushuaia.jpeg',
    price: 23123,
  },
  {
    id: 10,
    title: 'Laguna Torre',
    imgUrl: 'lagunatorre.jpeg',
    price: 23123,
  },
  {
    id: 11,
    title: 'Laguna Torre',
    imgUrl: 'lagunatorre.jpeg',
    price: 23123,
  },
  {
    id: 12,
    title: 'Laguna Torre',
    imgUrl: 'lagunatorre.jpeg',
    price: 23123,
  },
];